### ISSUE TITLE
[WIP] Redo the README

### ISSUE THREAD

**Issue by alisnichenko** [USFCEN4020/CEN4020F21TeamWyoming#2]
### Problem
Currently, the README (the small documentation file in the root of the project) contains outdated info about the project and almost no information about the code. I believe it would be useful to incorporate documentation about currently implemented functionality, exact specifications, and (maybe) a feature roadmap.

Let me know what you think, I will take a look at it today and submit a PR to review for the team

### Solution
* Add updated running instructions to the readme
* Add specifications and descriptions of existing files in the directory.
* Think about adding a roadmap with checklists and tentative deadlines (like in JIRA).

**Comment by Peacewalker365** [comment]
Hey Alex, I just added a flow chart to explain the UI logic, hope it will help a little.
And the documentation will be updated along the way.
