### ISSUE TITLE
[WIP] Enforce proper style

### ISSUE THREAD

**Issue by alisnichenko** [USFCEN4020/CEN4020F21TeamWyoming#3]
### Problem
Currently, the code doesn't conform to any known and well-established Python coding style, making it difficult to read the code and test it along the way.

### Solution
I propose rewriting the code using the following style that has been accepted for many years by multiple big players in the industry: https://google.github.io/styleguide/pyguide.html. We do not have to stick to it in its entirety, and I will demonstrate what I mean by that in the next PR that I will do.

**Comment by Peacewalker365** [comment]
Thanks for your feedback Alex, I'll read it and make the change afterward since my role will still be a developer next week.

**Comment by alisnichenko** [comment]
Don't worry, don't start on this while I haven't pushed my PR yet. We can hop on a call do discuss this.

**Comment by Peacewalker365** [comment]
Proper coding style enforced.
